# Fictional stocks
fictional_stocks = {
    "Food": ["Gourmet Foods", "Healthy Eats", "Snack World", "Organic Delights", "TastyTreats", "Farm Fresh", "Crispy Corners", "Chef's Choice"],
    "Pharmaceutical": ["MediLife", "PharmaPlus", "CureCo", "BioAdvance", "HealthGen", "LifeSavers Pharma", "VaccineVenture", "PillWorks"],
    "Tech": ["TechNova", "CyberSoft", "Quantum Systems", "NanoLogic", "DataSphere", "FutureTek", "SysX Innovations", "NextGen Solutions", "BlueChip Technologies"],
    "Energy": ["GreenEnergy", "PowerGrid", "Solaris Corp", "EcoFuel", "RenewGen", "VoltWind", "Terra Energy", "FusionPower"],
    "Defense": ["DefendTech", "SecureCorp", "ShieldWorks", "AeroDefense", "ArmorCo", "BattleGrid", "Tactical Innovations", "Vanguard Defense"],
    "Automotive": ["AutoDrive", "Speedster Motors", "HyperWheels", "Electric Motion", "TorqueMotors", "FusionDrive", "AutoFusion", "Prime Motors"],
    "Entertainment": ["FunTime", "StarMedia", "MovieMagic", "GameZone Studios", "EpicCinema", "DreamScape Productions", "Spectra Entertainment", "Big Screen Studios"],
    "Agriculture": ["AgriTech", "Corn Company", "Harvest Industries", "GreenGroves", "SeedGrow", "FertileFields", "EcoFarms", "FreshSprouts"],
    "Fashion": ["StyleFusion", "TrendWear", "Couture House", "Urban Outfitters", "ChicDesigns", "ModeWear", "FashionFrenzy", "RunwayStyles"],
    "Retail": ["ShopMore", "QuickMart", "MarketSpace", "DealFinders", "SuperBuy", "DiscountPlus", "RetailWorld", "DailyNeeds"],
    "Finance": ["WealthPro", "MoneyMakers", "InvestMax", "CreditLine Bank", "CapitalVision", "SafeInvest", "BankOnIt", "FortuneFund"],
    "Transportation": ["FastTrack", "Transo Logistics", "SkyCargo", "MetroLink", "JetExpress", "CargoMove", "HighwayHaul", "RapidRoute"],
    "Healthcare": ["HealthGuard", "Wellness Solutions", "VitalMed", "CareFirst", "HealingHands", "MediCareNet", "LifeAid Health", "Pathway Wellness"],
    "Telecommunications": ["GlobalNet", "WaveComm", "TalkSphere", "SignalNow", "CommConnect", "TeleGrid", "FastLink", "SatNet Communications"],
    "Real Estate": ["UrbanSpace", "Prime Properties", "EstateBuilders", "Skyline Ventures", "BrickWorks Realty", "HomeScape", "SkyRise Developments", "CityLiving"],
    "Consumer Goods": ["HomeEssentials", "Bright Appliances", "MegaClean", "HappyHome", "LivingLux", "ComfortWare", "FreshHome", "FreshLife Products"],
    "Gaming": ["Pixel Play", "Battle Arena", "VirtualVerse", "GameForge Studios", "EliteGamers", "RetroWave", "Arcadia Games", "FusionPlay"],
    "Biotech": ["GeneWorks", "LifeGen", "BioInnovations", "Cellular Tech", "MedGenome", "BioQuest", "NanoBiotics", "CellFusion"],
    "Aerospace": ["StarFlight", "OrbitCorp", "AeroSpace Dynamics", "LunarTech", "NovaSpace", "Cosmo Ventures", "Stratos Systems", "AstroFlight"],
    "Hospitality": ["GlobalStays", "Luxury Resorts", "CityEscapes", "Zen Hotels", "OceanView Resorts", "DreamStay Hotels", "Sunrise Hospitality", "EcoLodge"],
    "Insurance": ["SafeGuard Insurance", "LifeSecure", "ProtectPlus", "SureShield", "CoverAll", "RiskGuard", "InsureNow", "PrimeCare"],
    "E-commerce": ["BuyNow", "ShopNet", "InstantDeals", "QuickCart", "E-Shop World", "CartPlus", "OnlineBazaar", "WebMall"],
    "Media": ["InfoStream", "NewsNow", "PulseMedia", "GlobalNews", "FastWire", "BuzzNet", "PrimeReport", "UpdateX Media"],
    "Construction": ["BuildMax", "SteelWorks", "MegaConstruct", "Concrete Solutions", "Skyline Builders", "SolidBase", "PrimeConstruct", "UrbanBuild"],
    "Chemicals": ["ChemCo", "FusionChem", "BioChemTech", "SafeChem", "Johnson Compounds", "ElementalTech", "SynthoSolutions", "InnovativeChem"],
    "Mining": ["GoldWorks", "RockSolid Mining", "TerraMines", "MineralMax", "IronStone", "DeepDigs", "GlobalExtraction", "Gemstone Resources"],
    "Logistics": ["QuickShip", "CargoFleet", "TransLogix", "EasyFreight", "ShipIt Logistics", "GlobalFreight", "SpeedyShip", "LogiMax"],
    "Education": ["BrightMinds", "FutureLearn", "Global Academy", "EduCorp", "KnowledgePath", "SkillPro", "MentorMe", "NextStep Learning"],
    "Luxury Goods": ["EliteDesigns", "GoldenTouch", "DiamondWorks", "LuxuryEssentials", "PrestigeLuxe", "RoyalCollection", "VelvetCraft", "Opulent Brands"],
}



news_dict = {
    "NextGen Solutions introduces revolutionary home computer, stock soars": ("Stock", "NextGen Solutions", 1),
    "Automotive sector accelerates as demand for muscle cars revs up": ("Category", "Automotive", 1),
    "Arcadia Games' latest console causes craze; lines wrap around city blocks": ("Stock", "Arcadia Games", 1),
    "Tech sector rattled by floppy disk shortage halting production": ("Category", "Tech", -1.5),
    "BioAdvance claims cure for common cold; scientists skeptical": ("Stock", "BioAdvance", 1),
    "Energy sector boosted by discovery of massive oil reserves in Alaska": ("Category", "Energy", 1),
    "NanoLogic's microchip breakthrough doubles computing power": ("Stock", "NanoLogic", 1),
    "Fashion industry dazzled as neon colors dominate runways": ("Category", "Fashion", 1),
    "FusionDrive unveils sports car breaking speed records": ("Stock", "FusionDrive", 1),
    "Media sector abuzz over VHS tapes revolutionizing home entertainment": ("Category", "Media", 1),
    "DefendTech accused of selling outdated equipment to military": ("Stock", "DefendTech", -1.5),
    "Healthcare sector faces scrutiny over rising insurance premiums": ("Category", "Healthcare", -1.5),
    "WaveComm's mobile phone becomes ultimate status symbol despite size": ("Stock", "WaveComm", 1),
    "Mining sector hit by labor strikes across multiple countries": ("Category", "Mining", -1.5),
    "BankOnIt faces allegations of insider trading": ("Stock", "BankOnIt", -1.5),
    "RetailWorld announces 'biggest sale ever'; shoppers rejoice": ("Stock", "RetailWorld", 1),
    "FastLink's new pager expected to change communication forever": ("Stock", "FastLink", 1),
    "LuxuryEssentials sells out limited edition watches in record time": ("Stock", "LuxuryEssentials", 1),
    "Gaming sector shaken by video game crash; companies scramble": ("Category", "Gaming", -1.5),
    "PharmaPlus's diet pill promises miracles; FDA expresses concern": ("Stock", "PharmaPlus", -1.5),
    "Transportation sector celebrates as new highway reduces travel times": ("Category", "Transportation", 1),
    "EcoFuel develops alternative fuel from algae; stock rises": ("Stock", "EcoFuel", 1),
    "Entertainment sector thrives with blockbuster summer hits": ("Category", "Entertainment", 1),
    "StarMedia's latest film breaks box office records": ("Stock", "StarMedia", 1),
    "Automotive sector fears imports as Japanese cars gain popularity": ("Category", "Automotive", -1.5),
    "TorqueMotors recalls vehicles over safety concerns": ("Stock", "TorqueMotors", -1.5),
    "Food sector sees surge in microwave meal popularity": ("Category", "Food", 1),
    "Gourmet Foods launches line of instant dinners": ("Stock", "Gourmet Foods", 1),
    "Finance sector excited as stock market reaches all-time high": ("Category", "Finance", 1),
    "WealthPro introduces revolutionary investment strategy": ("Stock", "WealthPro", 1),
    "Telecommunications sector expands with fiber optic advancements": ("Category", "Telecommunications", 1),
    "GlobalNet connects cities with high-speed internet": ("Stock", "GlobalNet", 1),
    "Agriculture sector struggles with farm debt crisis": ("Category", "Agriculture", -1.5),
    "Harvest Industries faces bankruptcy amid economic downturn": ("Stock", "Harvest Industries", -1.5),
    "Energy sector worried as oil prices plummet": ("Category", "Energy", -1.5),
    "PowerGrid's profits decline due to cheaper alternatives": ("Stock", "PowerGrid", -1.5),
    "DefendTech secures billion-dollar defense contract": ("Stock", "DefendTech", 1),
    "FashionFrenzy launches iconic denim line; becomes instant hit": ("Stock", "FashionFrenzy", 1),
    "E-commerce sector in infancy; skeptics doubt its future": ("Category", "E-commerce", -1.5),
    "BuyNow pioneers online shopping experience": ("Stock", "BuyNow", 1),
    "Healthcare sector optimistic with new medical technologies": ("Category", "Healthcare", 1),
    "LifeAid Health introduces MRI machines to hospitals": ("Stock", "LifeAid Health", 1),
    "Insurance sector faces claims after natural disasters": ("Category", "Insurance", -1.5),
    "SafeGuard Insurance handles record number of claims": ("Stock", "SafeGuard Insurance", -1.5),
    "Construction sector booms with urban development projects": ("Category", "Construction", 1),
    "Skyline Builders awarded contract for tallest skyscraper": ("Stock", "Skyline Builders", 1),
    "TechNova develops compact disc technology; changes music industry": ("Stock", "TechNova", 1),
    "Media sector shifts focus to 14-hour news cycles": ("Category", "Media", 1),
    "NewsNow launches around-the-clock broadcasting": ("Stock", "NewsNow", 1),
    "Automotive sector experiments with hydrogen fuel cells": ("Category", "Automotive", 0.5),
    "Electric Motion invests heavily in alternative energy vehicles": ("Stock", "Electric Motion", 1),
    "Pharmaceutical sector advances with AIDS research": ("Category", "Pharmaceutical", 1),
    "MediLife's new treatment offers hope to patients": ("Stock", "MediLife", 1),
    "Entertainment sector faces backlash over violent content": ("Category", "Entertainment", -1.5),
    "EpicCinema delays controversial film release": ("Stock", "EpicCinema", -1.5),
    "Logistics sector revolutionized by barcode scanning": ("Category", "Logistics", 1),
    "QuickShip implements new tracking system; increases efficiency": ("Stock", "QuickShip", 1),
    "Telecommunications sector excited over satellite phone prospects": ("Category", "Telecommunications", 1),
    "SatNet Communications launches first mobile satellite": ("Stock", "SatNet Communications", 1),
    "Mining sector benefits from high demand for precious metals": ("Category", "Mining", 1),
    "Gemstone Resources discovers large diamond deposit": ("Stock", "Gemstone Resources", 1),
    "Retail sector threatened by big-box store expansion": ("Category", "Retail", -1.5),
    "DailyNeeds struggles to compete with larger chains": ("Stock", "DailyNeeds", -1.5),
    "Fashion industry embraces shoulder pads; consumers perplexed": ("Category", "Fashion", 1),
    "Urban Outfitters capitalizes on latest fashion trends": ("Stock", "Urban Outfitters", 1),
    "Transportation sector excited about Concorde's supersonic flights": ("Category", "Transportation", 1),
    "SkyCargo explores high-speed cargo delivery": ("Stock", "SkyCargo", 1),
    "Chemicals sector faces environmental regulation challenges": ("Category", "Chemicals", -1.5),
    "SafeChem fined for pollution violations": ("Stock", "SafeChem", -1.5),
    "Education sector expands with computer-based learning": ("Category", "Education", 1),
    "EduCorp introduces PCs into classrooms": ("Stock", "EduCorp", 1),
    "Hospitality sector thrives with rise of luxury resorts": ("Category", "Hospitality", 1),
    "OceanView Resorts opens new location in the Caribbean": ("Stock", "OceanView Resorts", 1),
    "Finance sector cautious as savings and loan crisis unfolds": ("Category", "Finance", -1.5),
    "MoneyMakers affected by banking regulations": ("Stock", "MoneyMakers", -1.5),
    "Food sector innovates with 'low-fat' products": ("Category", "Food", 1),
    "Healthy Eats launches successful line of diet foods": ("Stock", "Healthy Eats", 1),
    "Gaming sector revives with introduction of 16-bit consoles": ("Category", "Gaming", 1),
    "Battle Arena releases game that defines a generation": ("Stock", "Battle Arena", 1),
    "Telecommunications sector competes over long-distance calling rates": ("Category", "Telecommunications", -1.5),
    "CommConnect undercuts competitors with lower rates": ("Stock", "CommConnect", 1),
    "Real Estate market booms with suburban expansion": ("Category", "Real Estate", 1),
    "Prime Properties sells out new housing development": ("Stock", "Prime Properties", 1),
    "Consumer Goods sector benefits from 'as seen on TV' craze": ("Category", "Consumer Goods", 1),
    "Bright Appliances' new gadget becomes household staple": ("Stock", "Bright Appliances", 1),
    "Biotech sector explores genetic engineering possibilities": ("Category", "Biotech", 1),
    "GeneWorks pioneers gene splicing techniques": ("Stock", "GeneWorks", 1),
    "Aerospace sector excited by Space Shuttle launches": ("Category", "Aerospace", 1),
    "StarFlight collaborates with NASA on new missions": ("Stock", "StarFlight", 1),
    "Insurance sector adapts to increased life expectancy": ("Category", "Insurance", 1),
    "LifeSecure offers new long-term policies": ("Stock", "LifeSecure", 1),
    "E-commerce concept met with skepticism by traditional retailers": ("Category", "E-commerce", -1.5),
    "InstantDeals tries to convince investors of online potential": ("Stock", "InstantDeals", -1.5),
    "Media sector faces challenges from cable television rise": ("Category", "Media", -1.5),
    "InfoStream loses viewers to specialized channels": ("Stock", "InfoStream", -1.5),
    "Construction sector hit by asbestos regulation changes": ("Category", "Construction", -1.5),
    "Concrete Solutions halts projects for safety inspections": ("Stock", "Concrete Solutions", -1.5),
    "Chemicals sector explores plastics for new applications": ("Category", "Chemicals", 1),
    "Johnson Compounds develops stronger, lighter materials": ("Stock", "Johnson Compounds", 1),
    "Mining sector faces equipment shortages": ("Category", "Mining", -1.5),
    "DeepDigs delays operations due to machinery issues": ("Stock", "DeepDigs", -1.5),
    "Logistics sector booms with globalization trends": ("Category", "Logistics", 1),
    "GlobalFreight expands routes to Asia": ("Stock", "GlobalFreight", 1),
    "Education sector debates standardized testing merits": ("Category", "Education", -1.5),
    "KnowledgePath advocates for alternative assessments": ("Stock", "KnowledgePath", 1),
    "Luxury Goods sector flourishes with high consumer confidence": ("Category", "Luxury Goods", 1),
    "GoldenTouch's jewelry sales hit record highs": ("Stock", "GoldenTouch", 1),
    "Food sector hit by concerns over preservatives": ("Category", "Food", -1.5),
    "Organic Delights gains popularity amid health scares": ("Stock", "Organic Delights", 1),
    "Pharmaceutical sector develops groundbreaking antibiotics": ("Category", "Pharmaceutical", 1),
    "CureCo's new drug fights resistant bacteria": ("Stock", "CureCo", 1),
    "Tech sector excited by rise of personal computing": ("Category", "Tech", 1),
    "BlueChip Technologies dominates PC market": ("Stock", "BlueChip Technologies", 1),
    "Energy sector worried about nuclear power perception": ("Category", "Energy", -1.5),
    "FusionPower reassures public after minor plant incident": ("Stock", "FusionPower", -1.5),
    "Defense sector bolstered by increased military spending": ("Category", "Defense", 1),
    "ArmorCo's stock rises with new government contracts": ("Stock", "ArmorCo", 1),
    "Automotive sector explores turbocharged engines": ("Category", "Automotive", 1),
    "Speedster Motors introduces turbo model; enthusiasts thrilled": ("Stock", "Speedster Motors", 1),
    "Entertainment sector embraces MTV generation": ("Category", "Entertainment", 1),
    "DreamScape Productions produces hit music videos": ("Stock", "DreamScape Productions", 1),
    "Agriculture sector adapts to high-tech equipment": ("Category", "Agriculture", 1),
    "SeedGrow develops automated planting systems": ("Stock", "SeedGrow", 1),
    "Fashion industry shocked by 'grunge' style emergence": ("Category", "Fashion", -1.5),
    "Couture House struggles to adapt to changing tastes": ("Stock", "Couture House", -1.5),
    "Retail sector benefits from mall culture explosion": ("Category", "Retail", 1),
    "QuickMart opens stores in major shopping centers": ("Stock", "QuickMart", 1),
    "Finance sector enjoys profits from junk bond sales": ("Category", "Finance", 1),
    "CapitalVision invests heavily in high-yield bonds": ("Stock", "CapitalVision", 1),
    "Transportation sector sees rise in air travel demand": ("Category", "Transportation", 1),
    "MetroLink expands services to additional cities": ("Stock", "MetroLink", 1),
    "Healthcare sector debates HMOs and patient care": ("Category", "Healthcare", -1.5),
    "Pathway Wellness advocates for patient rights": ("Stock", "Pathway Wellness", 1),
    "Telecommunications sector faces breakup of monopolies": ("Category", "Telecommunications", -1.5),
    "TeleGrid adjusts strategies post-regulation changes": ("Stock", "TeleGrid", -1.5),
    "Real Estate sector concerned over bubble warnings": ("Category", "Real Estate", -1.5),
    "EstateBuilders slows down new projects amid market fears": ("Stock", "EstateBuilders", -1.5),
    "Consumer Goods sector capitalizes on fitness craze": ("Category", "Consumer Goods", 1),
    "ComfortWare's athletic apparel sees increased sales": ("Stock", "ComfortWare", 1),
    "Gaming sector faces parental backlash over content": ("Category", "Gaming", -1.5),
    "FusionPlay implements rating system to appease critics": ("Stock", "FusionPlay", 1),
    "Biotech sector explores cloning possibilities": ("Category", "Biotech", 1),
    "CellFusion's cloning experiments spark ethical debates": ("Stock", "CellFusion", -0.5),
    "Aerospace sector mourns after Challenger disaster": ("Category", "Aerospace", -1.5),
    "AeroSpace Dynamics reassesses safety protocols": ("Stock", "AeroSpace Dynamics", -1.5),
    "Hospitality sector adapts to business traveler needs": ("Category", "Hospitality", 1),
    "CityEscapes opens executive suites in major cities": ("Stock", "CityEscapes", 1),
    "Insurance sector deals with increased healthcare costs": ("Category", "Insurance", -1.5),
    "SureShield raises premiums to cover expenses": ("Stock", "SureShield", -1.5),
    "E-commerce sector overlooked as 'just a fad'": ("Category", "E-commerce", -1.5),
    "QuickCart insists online shopping is the future": ("Stock", "QuickCart", -1.5),
    "Media sector embraces talk radio popularity": ("Category", "Media", 1),
    "FastWire launches syndicated radio programs": ("Stock", "FastWire", 1),
    "Construction sector faces labor shortages": ("Category", "Construction", -1.5),
    "SolidBase increases wages to attract workers": ("Stock", "SolidBase", -1.5),
    "Chemicals sector improves safety standards": ("Category", "Chemicals", 1),
    "ElementalTech invests in employee training": ("Stock", "ElementalTech", 1),
    "Mining sector explores automation to increase output": ("Category", "Mining", 1),
    "IronStone invests in robotic mining equipment": ("Stock", "IronStone", 1),
    "Logistics sector utilizes GPS technology": ("Category", "Logistics", 1),
    "CargoFleet improves delivery times with new tech": ("Stock", "CargoFleet", 1),
    "Education sector debates 'new math' curriculum": ("Category", "Education", -1.5),
    "MentorMe supports traditional teaching methods": ("Stock", "MentorMe", 1),
    "Luxury Goods sector hurt by economic recession": ("Category", "Luxury Goods", -1.5),
    "PrestigeLuxe reports decline in sales": ("Stock", "PrestigeLuxe", -1.5),
    "Food sector experiences coffee shortage": ("Category", "Food", -1.5),
    "Farm Fresh raises prices due to supply issues": ("Stock", "Farm Fresh", -1.5),
    "Pharmaceutical sector investigates natural remedies": ("Category", "Pharmaceutical", 1),
    "PillWorks releases herbal supplement line": ("Stock", "PillWorks", 1),
    "Tech sector anticipates Y1K bug challenges": ("Category", "Tech", -1.5),
    "SysX Innovations offers solutions to Y1K problem": ("Stock", "SysX Innovations", 1),
    "Energy sector considers wind power investments": ("Category", "Energy", 1),
    "VoltWind builds first large-scale wind farm": ("Stock", "VoltWind", 1),
    "Defense sector develops stealth technology": ("Category", "Defense", 1),
    "ShieldWorks unveils new stealth aircraft": ("Stock", "ShieldWorks", 1),
    "Automotive sector excited by SUV popularity": ("Category", "Automotive", 1),
    "AutoDrive's new SUV becomes best-seller": ("Stock", "AutoDrive", 1),
    "Entertainment sector shifts focus to reality TV": ("Category", "Entertainment", 1),
    "Spectra Entertainment launches hit reality show": ("Stock", "Spectra Entertainment", 1),
    "Agriculture sector benefits from GMO crops": ("Category", "Agriculture", 1),
    "EcoFarms adopts GMO seeds to increase yield": ("Stock", "EcoFarms", 1),
    "Fashion industry goes minimalist; 'less is more'": ("Category", "Fashion", 1),
    "RunwayStyles leads with simple designs": ("Stock", "RunwayStyles", 1),
    "Retail sector embraces loyalty programs": ("Category", "Retail", 1),
    "DealFinders' rewards program attracts customers": ("Stock", "DealFinders", 1),
    "Finance sector faces competition from fintech startups": ("Category", "Finance", -1.5),
    "FortuneFund invests in new technologies": ("Stock", "FortuneFund", 1),
    "Transportation sector looks into magnetic levitation trains": ("Category", "Transportation", 1),
    "HighwayHaul explores maglev tech for freight": ("Stock", "HighwayHaul", 1),
    "Healthcare sector deals with malpractice lawsuits": ("Category", "Healthcare", -1.5),
    "HealingHands implements stricter protocols": ("Stock", "HealingHands", -1.5),
    "Telecommunications sector tests video calling capabilities": ("Category", "Telecommunications", 1),
    "SignalNow pioneers early video conferencing": ("Stock", "SignalNow", 1),
    "Real Estate sector adapts to 'McMansion' trend": ("Category", "Real Estate", 1),
    "UrbanSpace builds larger suburban homes": ("Stock", "UrbanSpace", 1),
    "Consumer Goods sector faces backlash over sweatshops": ("Category", "Consumer Goods", -1.5),
    "FreshLife Products commits to ethical sourcing": ("Stock", "FreshLife Products", 1),
    "Gaming sector experiments with virtual reality": ("Category", "Gaming", 0.75),
    "Pixel Play develops early VR headset prototype": ("Stock", "Pixel Play", 1),
    "Biotech sector researches human genome mapping": ("Category", "Biotech", 1),
    "MedGenome contributes to Human Genome Project": ("Stock", "MedGenome", 1),
    "Aerospace sector tests reusable spacecraft": ("Category", "Aerospace", 1),
    "NovaSpace designs shuttle for multiple missions": ("Stock", "NovaSpace", 1),
    "Hospitality sector caters to eco-tourism demand": ("Category", "Hospitality", 1),
    "Zen Hotels opens eco-friendly locations": ("Stock", "Zen Hotels", 1),
    "Insurance sector offers bundled policies": ("Category", "Insurance", 1),
    "CoverAll's package deals attract new clients": ("Stock", "CoverAll", 1),
    "E-commerce sector gains traction with young consumers": ("Category", "E-commerce", 1),
    "ShopNet reports increase in online sales": ("Stock", "ShopNet", 1),
    "Media sector explores satellite radio possibilities": ("Category", "Media", 1),
    "UpdateX Media invests in satellite technology": ("Stock", "UpdateX Media", 1),
    "Construction sector adopts CAD software": ("Category", "Construction", 1),
    "PrimeConstruct reduces design time with new tools": ("Stock", "PrimeConstruct", 1),
    "Chemicals sector faces competition from overseas": ("Category", "Chemicals", -1.5),
    "SynthoSolutions cuts costs to remain competitive": ("Stock", "SynthoSolutions", -1.5),
    "Mining sector benefits from increased gold prices": ("Category", "Mining", 1),
    "GlobalExtraction expands operations in Africa": ("Stock", "GlobalExtraction", 1),
    "Logistics sector tests RFID tracking": ("Category", "Logistics", 1),
    "SpeedyShip improves inventory management": ("Stock", "SpeedyShip", 1),
    "Education sector invests in teacher training": ("Category", "Education", 1),
    "SkillPro offers workshops to educators": ("Stock", "SkillPro", 1),
    "Luxury Goods sector partners with fashion houses": ("Category", "Luxury Goods", 1),
    "VelvetCraft collaborates with top designers": ("Stock", "VelvetCraft", 1),
    "TechNova launches first commercially successful CD player, stock skyrockets": ("Stock", "TechNova", 1),
    "Food sector rattled by unexpected rise in margarine prices": ("Category", "Food", -1.5),
    "Gourmet Foods introduces 'chocolate-covered broccoli'; consumers baffled": ("Stock", "Gourmet Foods", -1.5),
    "PharmaPlus secures FDA approval for new heart medication": ("Stock", "PharmaPlus", 1),
    "BioAdvance's laboratory accidentally creates super-strong adhesive, stock jumps": ("Stock", "BioAdvance", 1),
    "Energy sector excited by booming nuclear power investments": ("Category", "Energy", 1),
    "Solaris Corp's solar panels catch fire during demonstration, stock plummets": ("Stock", "Solaris Corp", -1.5),
    "DefendTech's new laser defense system hailed as 'unnecessary but cool'": ("Stock", "DefendTech", 1),
    "SecureCorp faces unexpected data breach, investor confidence shaken": ("Stock", "SecureCorp", -1.5),
    "Automotive sector celebrates the introduction of self-driving cars… in theory": ("Category", "Automotive", 1),
    "AutoDrive's prototype self-driving car fails spectacularly during test drive": ("Stock", "AutoDrive", -1.5),
    "Entertainment sector thrills with the release of the first-ever CD-ROM games": ("Category", "Entertainment", 1),
    "GameZone Studios accidentally releases unfinished game, players frustrated": ("Stock", "GameZone Studios", -1.5),
    "Agriculture sector benefits from genetically modified crops increasing yields": ("Category", "Agriculture", 1),
    "Corn Company faces backlash over GMO corn, sales dip": ("Stock", "Corn Company", -1.5),
    "Fashion sector dazzles with the comeback of shoulder pads and big hair": ("Category", "Fashion", 1),
    "StyleFusion's oversized blazers become overnight fashion sensation": ("Stock", "StyleFusion", 1),
    "Retail sector hit by shortage of neon signage materials": ("Category", "Retail", -1.5),
    "QuickMart runs out of popular cassette tapes, customers irate": ("Stock", "QuickMart", -1.5),
    "Finance sector optimistic as Wall Street hits new heights": ("Category", "Finance", 1),
    "InvestMax predicts bull market for next decade, investors ecstatic": ("Stock", "InvestMax", 1),
    "Transportation sector struggles with rising fuel costs affecting profitability": ("Category", "Transportation", -1.5),
    "SkyCargo's new jumbo jets face delays, stock declines": ("Stock", "SkyCargo", -1.5),
    "Healthcare sector applauds advances in MRI technology improving diagnostics": ("Category", "Healthcare", 1),
    "Wellness Solutions' new fitness craze leads to surge in gym memberships": ("Stock", "Wellness Solutions", 1),
    "Telecommunications sector overwhelmed by unexpected surge in fax machine sales": ("Category", "Telecommunications", 1),
    "TalkSphere's latest fax machine model malfunctions, returns increase": ("Stock", "TalkSphere", -1.5),
    "Real Estate sector flourishes with the rise of suburban developments": ("Category", "Real Estate", 1),
    "UrbanSpace's new suburban complexes sell out within weeks": ("Stock", "UrbanSpace", 1),
    "Consumer Goods sector faces criticism over excessive use of plastic packaging": ("Category", "Consumer Goods", -1.5),
    "MegaClean launches eco-friendly cleaning products, gains market share": ("Stock", "MegaClean", 1),
    "Gaming sector ecstatic as 16-bit consoles dominate the market": ("Category", "Gaming", 1),
    "VirtualVerse's 16-bit adventure game becomes instant classic": ("Stock", "VirtualVerse", 1),
    "Biotech sector explores controversial gene therapy techniques": ("Category", "Biotech", -1.5),
    "GeneWorks' gene therapy trial shows promising results, stock rises": ("Stock", "GeneWorks", 1),
    "Aerospace sector celebrates successful Space Shuttle mission": ("Category", "Aerospace", 1),
    "StarFlight's Space Shuttle launch faces minor technical issues but succeeds": ("Stock", "StarFlight", 1),
    "Hospitality sector thrives with the opening of new mega-resorts": ("Category", "Hospitality", 1),
    "GlobalStays' new mega-resort becomes the talk of the town": ("Stock", "GlobalStays", 1),
    "Insurance sector faces higher claims after severe winter storm": ("Category", "Insurance", -1.5),
    "ProtectPlus offers innovative home insurance packages, attracting new clients": ("Stock", "ProtectPlus", 1),
    "E-commerce sector struggles with low consumer trust in online shopping": ("Category", "E-commerce", -1.5),
    "BuyNow pioneers secure online payment systems, boosting consumer confidence": ("Stock", "BuyNow", 1),
    "Media sector experiences boom with the rise of cable TV networks": ("Category", "Media", 1),
    "NewsNow's 14-hour news channel attracts millions of viewers": ("Stock", "NewsNow", 1),
    "Construction sector hit by rising costs of steel and concrete": ("Category", "Construction", -1.5),
    "BuildMax innovates with cost-effective construction techniques, stock climbs": ("Stock", "BuildMax", 1),
    "Chemicals sector faces backlash over hazardous waste disposal practices": ("Category", "Chemicals", -1.5),
    "FusionChem develops non-toxic chemical alternatives, regains public trust": ("Stock", "FusionChem", 1),
    "Mining sector thrives with soaring gold prices": ("Category", "Mining", 1),
    "GoldWorks discovers new gold vein, stock surges": ("Stock", "GoldWorks", 1),
    "Logistics sector embraces barcode technology for efficient tracking": ("Category", "Logistics", 1),
    "CargoFleet implements barcode system, reduces delivery errors": ("Stock", "CargoFleet", 1),
    "Education sector debates the introduction of personal computers in classrooms": ("Category", "Education", 1),
    "BrightMinds secures funding for computer-based learning programs": ("Stock", "BrightMinds", 1),
    "Luxury Goods sector dazzles with the launch of diamond-encrusted gadgets": ("Category", "Luxury Goods", 1),
    "DiamondWorks releases diamond-studded wristwatch, becomes status symbol": ("Stock", "DiamondWorks", 1),
    "Food sector celebrates the introduction of microwave ovens revolutionizing cooking": ("Category", "Food", 1),
    "Healthy Eats launches microwave-ready healthy meal options, sales soar": ("Stock", "Healthy Eats", 1),
    "Pharmaceutical sector faces patent cliffs affecting major drug revenues": ("Category", "Pharmaceutical", -1.5),
    "CureCo develops new drug extending patent life, stock rebounds": ("Stock", "CureCo", 1),
    "Tech sector overwhelmed by rapid obsolescence of hardware": ("Category", "Tech", -1.5),
    "DataSphere's innovative hardware redesign extends product lifecycle": ("Stock", "DataSphere", 1),
    "Energy sector explores offshore drilling opportunities": ("Category", "Energy", 1),
    "VoltWind's offshore wind farm project approved, stock rises": ("Stock", "VoltWind", 1),
    "Defense sector benefits from increased military contracts": ("Category", "Defense", 1),
    "Vanguard Defense secures lucrative defense contracts, stock soars": ("Stock", "Vanguard Defense", 1),
    "Automotive sector hits roadblocks with rising environmental regulations": ("Category", "Automotive", -1.5),
    "Electric Motion adapts to regulations with eco-friendly vehicle lineup": ("Stock", "Electric Motion", 1),
    "Entertainment sector thrilled by the blockbuster success of 'Back to the Future'": ("Category", "Entertainment", 1),
    "EpicCinema's 'Back to the Future' sees record-breaking ticket sales": ("Stock", "EpicCinema", 1),
    "Agriculture sector struggles with invasive pest species affecting crops": ("Category", "Agriculture", -1.5),
    "FertileFields develops pest-resistant crops, mitigating losses": ("Stock", "FertileFields", 1),
    "Fashion sector lambasts oversized accessories trend": ("Category", "Fashion", -1.5),
    "ModeWear counters with sleek, minimalist accessory line, gaining popularity": ("Stock", "ModeWear", 1),
    "Retail sector sees decline in mall foot traffic due to rising online sales": ("Category", "Retail", -1.5),
    "SuperBuy integrates online shopping with physical stores, reversing decline": ("Stock", "SuperBuy", 1),
    "Finance sector alarmed by rising interest rates impacting loans": ("Category", "Finance", -1.5),
    "CapitalVision hedges investments to protect against interest rate hikes": ("Stock", "CapitalVision", 1),
    "Transportation sector excited by advancements in high-speed trains": ("Category", "Transportation", 1),
    "RapidRoute unveils high-speed train prototype, stock jumps": ("Stock", "RapidRoute", 1),
    "Healthcare sector celebrates breakthroughs in cancer treatment research": ("Category", "Healthcare", 1),
    "VitalMed's new cancer drug receives rave reviews, stock soars": ("Stock", "VitalMed", 1),
    "Telecommunications sector faces unexpected surge in landline sales": ("Category", "Telecommunications", 1),
    "CommConnect capitalizes on landline boom with innovative service packages": ("Stock", "CommConnect", 1),
    "Real Estate sector fears bubble as prices skyrocket uncontrollably": ("Category", "Real Estate", -1.5),
    "BrickWorks Realty implements cooling measures, stabilizes growth": ("Stock", "BrickWorks Realty", 0.5),
    "Consumer Goods sector thrives with rise of home entertainment systems": ("Category", "Consumer Goods", 1),
    "HappyHome's new home theater systems become household must-have": ("Stock", "HappyHome", 1),
    "Gaming sector faces criticism over excessive violence in video games": ("Category", "Gaming", -1.5),
    "Battle Arena introduces content rating system, appeasing critics": ("Stock", "Battle Arena", 1),
    "Biotech sector explores synthetic biology, pushing ethical boundaries": ("Category", "Biotech", -1.5),
    "Cellular Tech's synthetic biology breakthroughs attract major investments": ("Stock", "Cellular Tech", 1),
    "Aerospace sector dazzled by commercial space travel prospects": ("Category", "Aerospace", 1),
    "NovaSpace announces first commercial space tourism flight, stock rockets": ("Stock", "NovaSpace", 1),
    "Hospitality sector innovates with themed hotels attracting niche markets": ("Category", "Hospitality", 1),
    "Sunrise Hospitality's pirate-themed hotel opens to rave reviews": ("Stock", "Sunrise Hospitality", 1),
    "Insurance sector struggles with rising healthcare-related claims": ("Category", "Insurance", -1.5),
    "InsureNow launches comprehensive health insurance packages, gaining clients": ("Stock", "InsureNow", 1),
    "E-commerce sector experiences growing pains with first major data breaches": ("Category", "E-commerce", -2.5),
    "WebMall enhances security measures after recent breaches, regains trust": ("Stock", "WebMall", 1.5),
    "Media sector buzzed by the rise of reality TV shows": ("Category", "Media", 1),
    "PrimeReport's new reality show becomes overnight sensation": ("Stock", "PrimeReport", 1),
    "Construction sector overcomes labor shortages with innovative training programs": ("Category", "Construction", 1),
    "UrbanBuild's apprenticeship program reduces labor shortages, boosts productivity": ("Stock", "UrbanBuild", 1),
    "Chemicals sector faces scrutiny over toxic emissions from factories": ("Category", "Chemicals", -1.5),
    "InnovativeChem's green chemistry initiatives improve public image": ("Stock", "InnovativeChem", 1),
    "Mining sector reaps rewards from rare earth metals demand": ("Category", "Mining", 1),
    "RockSolid Mining secures rare earth metals contract, stock surges": ("Stock", "RockSolid Mining", 1),
    "Logistics sector innovates with early GPS navigation systems": ("Category", "Logistics", 1),
    "TransLogix's GPS integration reduces delivery times significantly": ("Stock", "TransLogix", 1),
    "Education sector embraces distance learning technologies": ("Category", "Education", 1),
    "NextStep Learning's online courses attract global students": ("Stock", "NextStep Learning", 1),
    "Luxury Goods sector faces decline as economic downturn affects spending": ("Category", "Luxury Goods", -1.5),
    "Opulent Brands introduces affordable luxury line to capture broader market": ("Stock", "Opulent Brands", 1),
    "Food sector innovates with introduction of ready-to-eat frozen dinners": ("Category", "Food", 1),
    "TastyTreats' frozen meal line becomes a household staple": ("Stock", "TastyTreats", 1),
    "Pharmaceutical sector praised for rapid AIDS drug development": ("Category", "Pharmaceutical", 1),
    "LifeSavers Pharma's new AIDS medication receives widespread acclaim": ("Stock", "LifeSavers Pharma", 1),
    "Tech sector faces challenges with rising costs of silicon chips": ("Category", "Tech", -1.5),
    "Quantum Systems secures bulk silicon supply, stabilizes production costs": ("Stock", "Quantum Systems", 0.60),
    "Energy sector explores geothermal energy sources": ("Category", "Energy", 1),
    "RenewGen's geothermal plant approved, promising sustainable energy": ("Stock", "RenewGen", 1),
    "Defense sector excited by advancements in missile technology": ("Category", "Defense", 1),
    "BattleGrid's new missile systems attract international contracts": ("Stock", "BattleGrid", 1),
    "Automotive sector celebrates the debut of compact cars gaining popularity": ("Category", "Automotive", 1),
    "HyperWheels' new compact model becomes best-seller among urban drivers": ("Stock", "HyperWheels", 1),
    "Entertainment sector thrilled by the rise of music video channels": ("Category", "Entertainment", 1),
    "StarMedia's music video division reports record viewership numbers": ("Stock", "StarMedia", 1),
    "Agriculture sector benefits from automated harvesting technologies": ("Category", "Agriculture", 1),
    "AgriTech's new automated harvester increases crop efficiency": ("Stock", "AgriTech", 1),
    "Fashion sector struggles with oversaturated accessory market": ("Category", "Fashion", -1.5),
    "Couture House innovates with multifunctional fashion accessories": ("Stock", "Couture House", 1),
    "Retail sector faces challenges from emerging discount retailers": ("Category", "Retail", -1.5),
    "DealFinders counters competition with unbeatable prices and deals": ("Stock", "DealFinders", 1),
    "Finance sector optimistic despite looming economic uncertainties": ("Category", "Finance", 1),
    "FortuneFund diversifies portfolio to mitigate economic risks": ("Stock", "FortuneFund", 1),
    "Transportation sector explores electric rail systems for urban areas": ("Category", "Transportation", 1),
    "CargoMove invests in electric rail technology, reducing emissions": ("Stock", "CargoMove", 1),
    "Healthcare sector celebrates reduction in infant mortality rates": ("Category", "Healthcare", 1),
    "Pathway Wellness introduces new maternal health programs, stock rises": ("Stock", "Pathway Wellness", 1),
    "Telecommunications sector debates the future of satellite vs. cable TV": ("Category", "Telecommunications", 0),
    "SatNet Communications invests heavily in satellite TV technology": ("Stock", "SatNet Communications", 1),
    "Real Estate sector sees rise in high-rise luxury apartments": ("Category", "Real Estate", 1),
    "Prime Properties' new high-rise towers sell out rapidly": ("Stock", "Prime Properties", 1),
    "Consumer Goods sector faces criticism over non-recyclable packaging": ("Category", "Consumer Goods", -1.5),
    "FreshHome introduces recyclable packaging options, regains consumer trust": ("Stock", "FreshHome", 1),
    "Gaming sector celebrates the introduction of multiplayer gaming experiences": ("Category", "Gaming", 1),
    "GameForge Studios releases hit multiplayer game, stock surges": ("Stock", "GameForge Studios", 1),
    "Biotech sector pioneers advancements in stem cell research": ("Category", "Biotech", 1),
    "NanoBiotics' stem cell treatments show promising clinical trial results": ("Stock", "NanoBiotics", 1),
    "Aerospace sector excited by advancements in jet propulsion technology": ("Category", "Aerospace", 1),
    "AeroSpace Dynamics' new jet engines hailed as industry breakthrough": ("Stock", "AeroSpace Dynamics", 1),
    "Hospitality sector innovates with all-inclusive resort packages": ("Category", "Hospitality", 1),
    "Luxury Resorts' all-inclusive packages attract international tourists": ("Stock", "Luxury Resorts", 1),
    "Insurance sector grapples with rising auto insurance claims": ("Category", "Insurance", -1.5),
    "RiskGuard implements new risk assessment models, reducing claims": ("Stock", "RiskGuard", 1),
    "E-commerce sector experiences explosive growth as more consumers go online": ("Category", "E-commerce", 1),
    "ShopNet's user-friendly platform attracts millions of new customers": ("Stock", "ShopNet", 1),
    "Media sector faces decline in newspaper subscriptions due to digital shift": ("Category", "Media", -1.5),
    "UpdateX Media launches digital subscription service, recovers subscriber base": ("Stock", "UpdateX Media", 1),
    "Construction sector pioneers eco-friendly building materials": ("Category", "Construction", 1),
    "PrimeConstruct's eco-friendly projects gain popularity, stock rises": ("Stock", "PrimeConstruct", 1),
    "Chemicals sector invests in research for biodegradable plastics": ("Category", "Chemicals", 1),
    "BioChemTech's biodegradable plastic product receives environmental awards": ("Stock", "BioChemTech", 1),
    "Mining sector benefits from surge in silver prices": ("Category", "Mining", 1),
    "Gemstone Resources' silver mining operations expand, stock surges": ("Stock", "Gemstone Resources", 1),
    "Logistics sector overcomes traffic congestion issues with new routing systems": ("Category", "Logistics", 1),
    "SpeedyShip's advanced routing systems improve delivery times significantly": ("Stock", "SpeedyShip", 1),
    "Education sector celebrates increased literacy rates thanks to new programs": ("Category", "Education", 1),
    "SkillPro's literacy programs receive national recognition, stock rises": ("Stock", "SkillPro", 1),
    "Luxury Goods sector innovates with high-tech jewelry integrating LEDs": ("Category", "Luxury Goods", 1),
    "VelvetCraft's LED-integrated jewelry becomes the latest fashion trend": ("Stock", "VelvetCraft", 1),
    "Food sector hit by unexpected avocado shortage, prices soar": ("Category", "Food", -1.5),
    "Snack World capitalizes on avocado shortage with creative alternatives": ("Stock", "Snack World", 1),
    "Pharmaceutical sector lauded for rapid response to emerging diseases": ("Category", "Pharmaceutical", 1),
    "MediLife's quick development of new vaccines saves lives, stock surges": ("Stock", "MediLife", 1),
    "Tech sector frustrated by slow adoption of new operating systems": ("Category", "Tech", -1.5),
    "CyberSoft releases user-friendly operating system, boosts market share": ("Stock", "CyberSoft", 1),
    "Energy sector debates the future of coal amidst environmental concerns": ("Category", "Energy", -1.5),
    "GreenEnergy shifts focus to cleaner energy sources, regains investor trust": ("Stock", "GreenEnergy", 1),
    "Defense sector excited by advancements in radar technology": ("Category", "Defense", 1),
    "ShieldWorks' new radar systems adopted by multiple countries, stock soars": ("Stock", "ShieldWorks", 1),
    "Automotive sector celebrates introduction of turbocharged engines": ("Category", "Automotive", 1),
    "TorqueMotors' turbocharged model becomes favorite among car enthusiasts": ("Stock", "TorqueMotors", 1),
    "Entertainment sector faces backlash over graphic content in new movies": ("Category", "Entertainment", -1.5),
    "DreamScape Productions introduces PG-1.51 ratings to appease parents": ("Stock", "DreamScape Productions", 1),
    "Agriculture sector thrives with introduction of hybrid seeds increasing yield": ("Category", "Agriculture", 1),
    "EcoFarms' hybrid seeds lead to record-breaking harvests, stock jumps": ("Stock", "EcoFarms", 1),
    "Fashion sector debates the longevity of neon colors trend": ("Category", "Fashion", 0),
    "ChicDesigns diversifies with both neon and pastel collections, maintaining sales": ("Stock", "ChicDesigns", 1),
    "Retail sector grapples with rising rent costs in major shopping districts": ("Category", "Retail", -2.5),
    "MarketSpace negotiates better leases, stabilizes operating costs": ("Stock", "MarketSpace", 0.85),
    "Finance sector celebrates the introduction of ATMs increasing banking convenience": ("Category", "Finance", 1),
    "CreditLine Bank's new ATM network attracts more customers, stock rises": ("Stock", "CreditLine Bank", 1),
    "Transportation sector excited about the potential of electric scooters": ("Category", "Transportation", 1),
    "JetExpress tests electric scooters for airport transfers, stock sees minor rise": ("Stock", "JetExpress", 1),
    "Healthcare sector innovates with the introduction of portable diagnostic devices": ("Category", "Healthcare", 1),
    "CareFirst's portable diagnostics gain popularity in remote areas, stock soars": ("Stock", "CareFirst", 1),
    "Telecommunications sector faces decline in rotary phone usage": ("Category", "Telecommunications", -1.5),
    "FastLink introduces push-button phones, regains market share": ("Stock", "FastLink", 1.5),
    "Real Estate sector sees rise in demand for high-tech smart homes": ("Category", "Real Estate", 1),
    "SkyRise Developments' smart homes feature automated lighting and security, stock jumps": ("Stock", "SkyRise Developments", 1),
    "Consumer Goods sector hit by recall of faulty household appliances": ("Category", "Consumer Goods", -1.5),
    "Bright Appliances swiftly handles recall, maintains consumer trust": ("Stock", "Bright Appliances", 1),
    "Gaming sector thrilled by the release of the first handheld consoles": ("Category", "Gaming", 1),
    "Pixel Play's handheld console becomes a hit among young gamers": ("Stock", "Pixel Play", 1),
    "Biotech sector explores revolutionary cloning technologies": ("Category", "Biotech", -1.5),
    "CellFusion faces ethical debates over cloning experiments, stock declines": ("Stock", "CellFusion", -1.5),
    "Aerospace sector celebrates the development of reusable rockets": ("Category", "Aerospace", 1),
    "AstroFlight's reusable rockets reduce space mission costs, stock soars": ("Stock", "AstroFlight", 1.5),
    "Hospitality sector innovates with extended-stay hotel options": ("Category", "Hospitality", 1),
    "CityEscapes' extended-stay hotels become favorite among traveling professionals": ("Stock", "CityEscapes", 1),
    "Insurance sector faces challenges with rising cyber-related claims": ("Category", "Insurance", -1.5),
    "SureShield develops robust cyber insurance policies, attracting tech companies": ("Stock", "SureShield", 1),
    "E-commerce sector pioneers the use of shopping carts online": ("Category", "E-commerce", 1),
    "QuickCart's intuitive online shopping cart increases user engagement": ("Stock", "QuickCart", 1),
    "Media sector grapples with the rise of reality TV overshadowing scripted shows": ("Category", "Media", -1.5),
    "BuzzNet's reality TV division launches hit show, boosts overall ratings": ("Stock", "BuzzNet", 1),
    "Construction sector adapts to new safety regulations, enhancing worker safety": ("Category", "Construction", 1),
    "SteelWorks implements advanced safety measures, reduces workplace accidents": ("Stock", "SteelWorks", 1),
    "Chemicals sector innovates with non-flammable chemical compounds": ("Category", "Chemicals", 1),
    "Johnson Compounds' non-flammable chemicals become industry standard, stock rises": ("Stock", "Johnson Compounds", 1),
    "Mining sector faces environmental protests over new mining sites": ("Category", "Mining", -1.5),
    "RockSolid Mining delays new site development due to protests, stock dips": ("Stock", "RockSolid Mining", -1.5),
    "Logistics sector celebrates the introduction of overnight shipping services": ("Category", "Logistics", 1),
    "GlobalFreight's overnight shipping service becomes industry benchmark": ("Stock", "GlobalFreight", 1),
    "Education sector excited by the introduction of multimedia learning tools": ("Category", "Education", 1),
    "EduCorp's multimedia learning tools enhance student engagement, stock rises": ("Stock", "EduCorp", 1),
    "Luxury Goods sector hit by counterfeit luxury items flooding the market": ("Category", "Luxury Goods", -1.5),
    "EliteDesigns implements anti-counterfeit technologies, restoring brand integrity": ("Stock", "EliteDesigns", 1),
    "Food sector celebrates the rise of international cuisines in mainstream markets": ("Category", "Food", 1),
    "TastyTreats launches line of international snacks, sales soar": ("Stock", "TastyTreats", 1),
    "Pharmaceutical sector lauds advancements in non-invasive surgery techniques": ("Category", "Pharmaceutical", 1),
    "PharmaPlus introduces cutting-edge non-invasive surgical tools, stock jumps": ("Stock", "PharmaPlus", 1),
    "Tech sector frustrated by frequent software bugs delaying product releases": ("Category", "Tech", -1.5),
    "SysX Innovations debuts bug-free software, regains market trust": ("Stock", "SysX Innovations", 1),
    "Energy sector explores biofuels as alternative energy sources": ("Category", "Energy", 1),
    "EcoFuel's biofuel production exceeds expectations, stock surges": ("Stock", "EcoFuel", 1),
    "Defense sector celebrates the development of next-gen fighter jets": ("Category", "Defense", 1),
    "AeroDefense's fighter jets receive high praise from military officials": ("Stock", "AeroDefense", 1),
    "Automotive sector hit by rising production costs of electric vehicles": ("Category", "Automotive", -1.5),
    "FusionDrive optimizes production costs, making EVs more affordable, stock rises": ("Stock", "FusionDrive", 1),
    "Entertainment sector thrives with the popularity of blockbuster franchises": ("Category", "Entertainment", 1),
    "Spectra Entertainment's new blockbuster franchise becomes cultural phenomenon": ("Stock", "Spectra Entertainment", 1),
    "Agriculture sector benefits from government subsidies for sustainable farming": ("Category", "Agriculture", 1),
    "GreenGroves receives subsidies to expand sustainable farming practices, stock jumps": ("Stock", "GreenGroves", 1),
    "Fashion sector debates the return of bell-bottom jeans": ("Category", "Fashion", 0),
    "RunwayStyles introduces modern bell-bottom jeans, gains trendy clientele": ("Stock", "RunwayStyles", 1),
    "Retail sector struggles with inventory management issues": ("Category", "Retail", -1.5),
    "ShopMore implements advanced inventory systems, reducing stockouts": ("Stock", "ShopMore", 1),
    "Finance sector alarmed by unexpected inflation rates affecting investments": ("Category", "Finance", -1.5),
    "SafeInvest launches inflation-protected investment options, attracting investors": ("Stock", "SafeInvest", 1),
    "Transportation sector excited by the introduction of electric buses": ("Category", "Transportation", 1),
    "Transo Logistics' electric buses reduce operational costs, stock rises": ("Stock", "Transo Logistics", 1),
    "Healthcare sector celebrates the introduction of insulin pumps for diabetes patients": ("Category", "Healthcare", 1),
    "LifeAid Health's insulin pumps improve patient quality of life, stock surges": ("Stock", "LifeAid Health", 1),
    "Telecommunications sector faces decline in payphone usage": ("Category", "Telecommunications", -1.5),
    "FastLink invests in mobile phone infrastructure to combat payphone decline": ("Stock", "FastLink", 1),
    "Real Estate sector sees boom in downtown high-rise developments": ("Category", "Real Estate", 1),
    "SkyRise Developments' downtown towers attract young professionals, stock jumps": ("Stock", "SkyRise Developments", 1),
    "Consumer Goods sector celebrates the rise of portable music players": ("Category", "Consumer Goods", 1),
    "Bright Appliances' portable CD players become top-selling items": ("Stock", "Bright Appliances", 1),
    "Gaming sector experiences a surge in arcade game popularity": ("Category", "Gaming", 1),
    "Battle Arena's new arcade game attracts crowds, stock surges": ("Stock", "Battle Arena", 1),
    "Biotech sector explores regenerative medicine, pushing scientific boundaries": ("Category", "Biotech", 1),
    "MedGenome's regenerative treatments show breakthrough results, stock soars": ("Stock", "MedGenome", 1),
    "Aerospace sector debates the feasibility of commercial space stations": ("Category", "Aerospace", -1.5),
    "Cosmo Ventures secures funding for commercial space station project, stock jumps": ("Stock", "Cosmo Ventures", 1),
    "Hospitality sector innovates with themed culinary experiences": ("Category", "Hospitality", 1),
    "OceanView Resorts' themed restaurants attract food enthusiasts, stock rises": ("Stock", "OceanView Resorts", 1),
    "Insurance sector faces challenges with rising liability claims": ("Category", "Insurance", -1.5),
    "CoverAll implements proactive claim management, reducing liabilities": ("Stock", "CoverAll", 1),
    "E-commerce sector celebrates the first millionth online transaction": ("Category", "E-commerce", 1),
    "OnlineBazaar reaches milestone of one million transactions, stock soars": ("Stock", "OnlineBazaar", 1),
    "Media sector shifts focus to interactive television formats": ("Category", "Media", 1),
    "BuzzNet launches interactive TV shows, engaging viewers like never before": ("Stock", "BuzzNet", 1),
    "Construction sector innovates with pre-fabricated building components": ("Category", "Construction", 1),
    "MegaConstruct's pre-fab buildings reduce construction time, stock rises": ("Stock", "MegaConstruct", 1),
    "Chemicals sector celebrates breakthroughs in water purification technologies": ("Category", "Chemicals", 1),
    "SynthoSolutions' water purification products gain international acclaim": ("Stock", "SynthoSolutions", 1),
    "Mining sector faces unexpected flood in new mining site, causing delays": ("Category", "Mining", -1.5),
    "DeepDigs overcomes flood challenges, resumes mining operations, stock stabilizes": ("Stock", "DeepDigs", 0.5),
    "Logistics sector embraces early forms of automated sorting systems": ("Category", "Logistics", 1),
    "LogiMax's automated sorting increases efficiency, reducing costs": ("Stock", "LogiMax", 1),
    "Education sector faces budget cuts impacting educational programs": ("Category", "Education", -1.5),
    "MentorMe secures additional funding to sustain educational initiatives, stock rises": ("Stock", "MentorMe", 1),
    "Luxury Goods sector introduces customizable luxury items for affluent consumers": ("Category", "Luxury Goods", 1),
    "RoyalCollection's customizable luxury items become highly sought after": ("Stock", "RoyalCollection", 1),
    "Food sector celebrates the rise of organic farming practices": ("Category", "Food", 1),
    "Organic Delights' organic products gain widespread popularity, stock surges": ("Stock", "Organic Delights", 1),
    "Pharmaceutical sector praised for affordable generic drug production": ("Category", "Pharmaceutical", 1),
    "PillWorks' generic drugs provide affordable options, increasing market share": ("Stock", "PillWorks", 1),
    "Tech sector excited by the introduction of the first touchscreen computers": ("Category", "Tech", 1),
    "FutureTek's touchscreen computer becomes industry standard, stock skyrockets": ("Stock", "FutureTek", 1),
    "Energy sector debates the viability of nuclear fusion as future energy source": ("Category", "Energy", 1),
    "FusionPower invests in nuclear fusion research, attracting investor interest": ("Stock", "FusionPower", 1),
    "Defense sector faces ethical debates over autonomous weapon systems": ("Category", "Defense", -1.5),
    "Tactical Innovations announces ethical guidelines for autonomous weapons, stock stabilizes": ("Stock", "Tactical Innovations", 0.5),
    "Automotive sector celebrates the introduction of power steering becoming standard": ("Category", "Automotive", 1),
    "Speedster Motors' power steering-equipped models receive positive reviews, stock rises": ("Stock", "Speedster Motors", 1),
    "Entertainment sector experiences decline in traditional radio listenership": ("Category", "Entertainment", -1.5),
    "DreamScape Productions launches hit podcast series, regains audience": ("Stock", "DreamScape Productions", 1),
    "Agriculture sector benefits from the introduction of crop rotation techniques": ("Category", "Agriculture", 1),
    "Harvest Industries' crop rotation programs increase yields, stock surges": ("Stock", "Harvest Industries", 1),
    "Fashion sector excited by the resurgence of vintage clothing trends": ("Category", "Fashion", 1),
    "Urban Outfitters capitalizes on vintage trends, sales spike": ("Stock", "Urban Outfitters", 1),
    "Retail sector faces challenges with rising utility costs impacting profitability": ("Category", "Retail", -1.5),
    "DailyNeeds implements energy-saving measures, reducing operating costs": ("Stock", "DailyNeeds", 1),
    "Finance sector praised for introducing innovative financial instruments": ("Category", "Finance", 1),
    "MoneyMakers' new financial instruments attract major investors, stock jumps": ("Stock", "MoneyMakers", 1),
    "Transportation sector explores the potential of electric bicycles": ("Category", "Transportation", 1),
    "HighwayHaul launches electric bicycle delivery fleet, reducing emissions": ("Stock", "HighwayHaul", 1),
    "Healthcare sector celebrates advancements in robotic surgery": ("Category", "Healthcare", 1),
    "HealingHands' robotic surgery systems improve patient outcomes, stock soars": ("Stock", "HealingHands", 1),
    "Telecommunications sector faces competition from emerging mobile carriers": ("Category", "Telecommunications", -1.5),
    "SatNet Communications launches competitive mobile plans, attracts new customers": ("Stock", "SatNet Communications", 1),
    "Real Estate sector sees increased demand for eco-friendly buildings": ("Category", "Real Estate", 1),
    "HomeScape's eco-friendly buildings become a market favorite, stock rises": ("Stock", "HomeScape", 1),
    "Consumer Goods sector hit by shortage of rare earth metals affecting production": ("Category", "Consumer Goods", -1.5),
    "FreshLife Products secures rare earth metal supply, resumes production, stock stabilizes": ("Stock", "FreshLife Products", 0.5),
    "Gaming sector celebrates the launch of the first 1D games": ("Category", "Gaming", 1),
    "Pixel Play's 1D game becomes a groundbreaking success, stock soars": ("Stock", "Pixel Play", 1),
    "Biotech sector explores regenerative agriculture techniques": ("Category", "Biotech", 1),
    "BioInnovations' regenerative agriculture products increase farm productivity, stock rises": ("Stock", "BioInnovations", 1),
    "Aerospace sector excited by the potential of unmanned aerial vehicles": ("Category", "Aerospace", 1),
    "AstroFlight's unmanned aerial vehicles prove successful in multiple missions, stock jumps": ("Stock", "AstroFlight", 1),
    "Hospitality sector faces challenges with rising operational costs": ("Category", "Hospitality", -1.5),
    "EcoLodge implements cost-saving measures without compromising quality, stock stabilizes": ("Stock", "EcoLodge", 0.5),
    "Insurance sector praised for quick claim settlements enhancing customer satisfaction": ("Category", "Insurance", 1),
    "RiskGuard's efficient claim processing attracts more clients, stock rises": ("Stock", "RiskGuard", 1),
    "E-commerce sector sees decline in early adopters fearing online fraud": ("Category", "E-commerce", -1.5),
    "ShopNet enhances security features, regains consumer trust, stock surges": ("Stock", "ShopNet", 1),
    "Media sector embraces the rise of music video programming": ("Category", "Media", 1),
    "PulseMedia's exclusive music video content attracts younger demographics, stock rises": ("Stock", "PulseMedia", 1),
    "Construction sector innovates with earthquake-resistant building designs": ("Category", "Construction", 1),
    "SteelWorks' earthquake-resistant structures become industry standard, stock jumps": ("Stock", "SteelWorks", 1),
    "Chemicals sector faces challenges with volatile raw material prices": ("Category", "Chemicals", -1.5),
    "Johnson Compounds secures long-term contracts stabilizing revenue, stock rises": ("Stock", "Johnson Compounds", 0.6),
    "Mining sector benefits from technological advancements in ore extraction": ("Category", "Mining", 1),
    "MineralMax introduces automated ore extraction systems, increasing output, stock surges": ("Stock", "MineralMax", 1),
    "Logistics sector excited by the potential of containerization revolutionizing shipping": ("Category", "Logistics", 1),
    "TransLogix pioneers containerization techniques, reducing shipping costs, stock jumps": ("Stock", "TransLogix", 1),
    "Education sector faces backlash over standardized testing methodologies": ("Category", "Education", -1.5),
    "KnowledgePath introduces alternative assessment methods, improving student engagement": ("Stock", "KnowledgePath", 1),
    "Luxury Goods sector sees surge in demand for limited-edition collectibles": ("Category", "Luxury Goods", 1),
    "RoyalCollection's limited-edition collectibles sell out instantly, stock soars": ("Stock", "RoyalCollection", 1),
    "Food sector celebrates the introduction of frozen pizza becoming a household favorite": ("Category", "Food", 1),
    "Snack World launches gourmet frozen pizzas, sales skyrocket": ("Stock", "Snack World", 1),
    "Pharmaceutical sector lauded for affordable generic medications improving accessibility": ("Category", "Pharmaceutical", 1),
    "PillWorks' generic medications expand market reach, stock rises": ("Stock", "PillWorks", 1),
    "Tech sector faces decline in personal computer sales due to economic slowdown": ("Category", "Tech", -1.5),
    "BlueChip Technologies introduces budget-friendly PCs, regains market share": ("Stock", "BlueChip Technologies", 1),
    "Energy sector explores tidal energy as new sustainable source": ("Category", "Energy", 1),
    "RenewGen's tidal energy projects show promising results, stock rises": ("Stock", "RenewGen", 1),
    "Defense sector innovates with lightweight armor materials": ("Category", "Defense", 1),
    "ArmorCo's lightweight armor gains popularity with military contracts, stock surges": ("Stock", "ArmorCo", 1),
    "Automotive sector hit by oil embargo, production slows down": ("Category", "Automotive", -1.5),
    "FusionDrive secures alternative fuel sources, resumes full-scale production, stock stabilizes": ("Stock", "FusionDrive", 0.5),
    "Entertainment sector celebrates the rise of blockbuster action movies": ("Category", "Entertainment", 1),
    "Spectra Entertainment's action movie franchise breaks box office records, stock jumps": ("Stock", "Spectra Entertainment", 1),
    "Agriculture sector benefits from precision farming technologies increasing efficiency": ("Category", "Agriculture", 1),
    "AgriTech's precision farming tools become essential for modern farms, stock surges": ("Stock", "AgriTech", 1),
    "Fashion sector struggles with the high cost of imported fabrics": ("Category", "Fashion", -1.5),
    "ChicDesigns sources local fabrics to reduce costs, maintains profitability": ("Stock", "ChicDesigns", 1),
    "Retail sector celebrates the introduction of electronic cash registers increasing efficiency": ("Category", "Retail", 1),
    "QuickMart's new electronic cash registers reduce checkout times, stock rises": ("Stock", "QuickMart", 1),
    "Finance sector faces increased competition from emerging investment firms": ("Category", "Finance", -1.5),
    "BankOnIt expands services to compete, attracts new investors, stock jumps": ("Stock", "BankOnIt", 1),
    "Transportation sector excited by the potential of electric motorcycles": ("Category", "Transportation", 1),
    "Electric Motion's electric motorcycles gain traction among young riders, stock rises": ("Stock", "Electric Motion", 1),
    "Healthcare sector lauds advancements in non-invasive diagnostic tools": ("Category", "Healthcare", 1),
    "CareFirst's new diagnostic tools improve patient outcomes, stock surges": ("Stock", "CareFirst", 1),
    "Telecommunications sector faces challenges with aging infrastructure": ("Category", "Telecommunications", -1.5),
    "TeleGrid invests in modernizing infrastructure, improving service quality, stock rises": ("Stock", "TeleGrid", 1),
    "Real Estate sector sees increased interest in mixed-use developments": ("Category", "Real Estate", 1),
    "EstateBuilders' mixed-use developments attract diverse tenants, stock jumps": ("Stock", "EstateBuilders", 1),
    "Consumer Goods sector celebrates the rise of health-conscious products": ("Category", "Consumer Goods", 1),
    "Healthy Eats' health-conscious products become top sellers, stock surges": ("Stock", "Healthy Eats", 1),
    "Gaming sector thrilled by the introduction of first-person shooter games": ("Category", "Gaming", 1),
    "VirtualVerse's first-person shooter game sets new sales records, stock soars": ("Stock", "VirtualVerse", 1),
    "Biotech sector explores advanced tissue engineering techniques": ("Category", "Biotech", 1),
    "MedGenome's tissue engineering breakthroughs attract major investments, stock jumps": ("Stock", "MedGenome", 1),
    "Aerospace sector innovates with silent jet engine technology": ("Category", "Aerospace", 1),
    "AeroSpace Dynamics' silent jet engines receive positive industry reviews, stock rises": ("Stock", "AeroSpace Dynamics", 1),
    "Hospitality sector faces decline in business travel due to economic downturn": ("Category", "Hospitality", -1.5),
    "GlobalStays introduces budget-friendly business travel packages, stock stabilizes": ("Stock", "GlobalStays", 0.5),
    "Insurance sector praised for introducing customizable insurance plans": ("Category", "Insurance", 1),
    "CoverAll's customizable plans attract diverse clientele, stock rises": ("Stock", "CoverAll", 1),
    "E-commerce sector struggles with limited online payment options": ("Category", "E-commerce", -1.5),
    "CartPlus partners with major banks to expand payment options, stock jumps": ("Stock", "CartPlus", 1),
    "Media sector celebrates the rise of investigative journalism increasing credibility": ("Category", "Media", 1),
    "InfoStream's investigative reports gain national attention, stock surges": ("Stock", "InfoStream", 1),
    "Construction sector innovates with eco-friendly concrete mixtures": ("Category", "Construction", 1),
    "Concrete Solutions' eco-friendly concrete reduces environmental impact, stock rises": ("Stock", "Concrete Solutions", 1),
    "Chemicals sector faces challenges with volatile global chemical prices": ("Category", "Chemicals", -1.5),
    "ElementalTech hedges against price volatility, stabilizing revenue, stock maintains": ("Stock", "ElementalTech", 0.5),
    "Mining sector celebrates the discovery of a rare mineral deposit": ("Category", "Mining", 1),
    "TerraMines uncovers rare mineral deposit, stock skyrockets": ("Stock", "TerraMines", 1),
    "Logistics sector excited by the introduction of real-time tracking systems": ("Category", "Logistics", 1),
    "ShipIt Logistics' real-time tracking enhances customer satisfaction, stock rises": ("Stock", "ShipIt Logistics", 1),
    "Education sector embraces the use of educational television programs": ("Category", "Education", 1),
    "BrightMinds' educational TV programs receive positive feedback, stock jumps": ("Stock", "BrightMinds", 1),
    "Luxury Goods sector hit by decline in consumer spending on luxury items": ("Category", "Luxury Goods", -1.5),
    "Opulent Brands introduces affordable luxury lines to capture new markets, stock stabilizes": ("Stock", "Opulent Brands", 0.5),
    "Food sector innovates with the introduction of frozen vegetables becoming mainstream": ("Category", "Food", 1),
    "Farm Fresh's frozen vegetables see increased sales, stock rises": ("Stock", "Farm Fresh", 1),
    "Pharmaceutical sector lauded for rapid development of flu vaccines": ("Category", "Pharmaceutical", 1),
    "CureCo's flu vaccine distributed nationwide, stock surges": ("Stock", "CureCo", 1),
    "Tech sector faces decline in mainframe computer sales due to PC rise": ("Category", "Tech", -1.5),
    "Quantum Systems diversifies with innovative PC solutions, stock recovers": ("Stock", "Quantum Systems", 1),
    "Energy sector explores the potential of wave energy as sustainable source": ("Category", "Energy", 1),
    "VoltWind's wave energy projects gain international interest, stock jumps": ("Stock", "VoltWind", 1),
    "Defense sector excited by the development of advanced radar systems": ("Category", "Defense", 1),
    "SecureCorp's advanced radar systems adopted by multiple countries, stock soars": ("Stock", "SecureCorp", 1),
    "Automotive sector celebrates the introduction of power windows as standard feature": ("Category", "Automotive", 1),
    "HyperWheels' power window-equipped cars become customer favorites, stock rises": ("Stock", "HyperWheels", 1),
    "Entertainment sector faces decline in VHS sales due to DVD innovations": ("Category", "Entertainment", -1.5),
    "MovieMagic introduces DVD rentals, recovers VHS sales, stock stabilizes": ("Stock", "MovieMagic", 1),
    "Agriculture sector benefits from the introduction of automated irrigation systems": ("Category", "Agriculture", 1),
    "FertileFields' automated irrigation systems increase crop yields, stock jumps": ("Stock", "FertileFields", 1),
    "Fashion sector innovates with the introduction of stretch fabrics enhancing comfort": ("Category", "Fashion", 1),
    "RunwayStyles' stretch fabric clothing line gains popularity, stock rises": ("Stock", "RunwayStyles", 1),
    "Retail sector celebrates the introduction of loyalty reward programs": ("Category", "Retail", 1),
    "ShopMore's loyalty program attracts repeat customers, stock surges": ("Stock", "ShopMore", 1),
    "Finance sector faces challenges with increased regulatory requirements": ("Category", "Finance", -1.5),
    "SafeInvest complies with new regulations, maintains investor trust, stock stabilizes": ("Stock", "SafeInvest", 0.5),
    "Transportation sector explores the use of hybrid engines in public transport": ("Category", "Transportation", 1),
    "RapidRoute's hybrid engine buses reduce fuel consumption, stock rises": ("Stock", "RapidRoute", 1),
    "Healthcare sector celebrates the introduction of anti-retroviral therapies": ("Category", "Healthcare", 1),
    "VitalMed's anti-retroviral therapies improve patient outcomes, stock surges": ("Stock", "VitalMed", 1),
    "Telecommunications sector excited by the introduction of digital phone lines": ("Category", "Telecommunications", 1),
    "GlobalNet's digital phone lines offer clearer calls, attracting customers, stock jumps": ("Stock", "GlobalNet", 1),
    "Real Estate sector faces challenges with rising property taxes impacting sales": ("Category", "Real Estate", -1.5),
    "HomeScape lobbies for property tax reductions, maintains steady sales": ("Stock", "HomeScape", 1),
    "Consumer Goods sector innovates with the introduction of microwave-safe containers": ("Category", "Consumer Goods", 1),
    "FreshLife Products' microwave-safe containers become kitchen essentials, stock rises": ("Stock", "FreshLife Products", 1),
    "Gaming sector thrilled by the launch of the first online multiplayer games": ("Category", "Gaming", 1),
    "GameForge Studios' online multiplayer game attracts global players, stock surges": ("Stock", "GameForge Studios", 1),
    "Biotech sector explores advancements in personalized medicine": ("Category", "Biotech", 1),
    "LifeGen's personalized medicine solutions improve patient care, stock jumps": ("Stock", "LifeGen", 1),
    "Aerospace sector celebrates advancements in satellite communication technologies": ("Category", "Aerospace", 1),
    "OrbitCorp's new satellite communication systems revolutionize global connectivity, stock soars": ("Stock", "OrbitCorp", 1)}




graph_time_scales = {
    "1 day": 10,
    "1 week": 110,
    "1 month": 900,
    "6 months": 5400,
    "history": None
}



cheesy_slogans = [
    "Can you beat the market?",
    "You could be the next stock man!",
    "Think you’ve got what it takes to own Wall Street?",
    "The bulls are running… Are you?",
    "Fortune favors the bold! Ready to cash in?",
    "Buy low, sell high, live fast!",
    "Money never sleeps… and neither should you!",
    "The stock market waits for no one!",
    "Feeling lucky? Spin the financial wheel!",
    "Only the fearless survive the trading floor!",
    "Could you be the next Master of the Market?",
    "From rags to riches… if you play it right!",
    "Don’t just watch the ticker… be the ticker!",
    "Stocks are climbing… Are you?",
    "Trade fast, live large, retire rich!",
    "Welcome to the world of high stakes and high rewards!",
    "Cash in, cash out—make the market yours!",
    "Fortunes are made in minutes! Is yours one of them?",
    "The market is your playground… time to swing!",
    "Risk it all for the big win!",
    "It’s a stock jungle out there. Can you be the king?",
    "From the trading floor to the penthouse!",
    "Will your portfolio stand the test of time?",
    "Market glory awaits the brave!",
    "When the bell rings, the game begins!",
    "Fortune is just a trade away!",
    "The hustle never stops on Wall Street!",
    "You can’t win if you don’t play!",
    "Chase your dreams, one stock at a time!",
    "Do you have the guts to go all in?",
    "This is where fortunes are forged!",
    "Step up, trade hard, and take charge!",
    "The ticker's ticking—time to make a move!",
    "Can you handle the heat of the trading floor?",
    "From small-time to big-time… are you ready?",
    "Who needs luck when you have strategy?",
    "Trade like a shark, feast like a king!",
    "One trade can change everything!",
    "The market is wild—are you bold enough?",
    "The stock market is your battlefield!",
    "Turn your pennies into millions!",
    "Step into the ring and take on the market!",
    "Profit is the name of the game!",
    "The market is your stage—time to perform!",
    "Watch your wealth soar as you master the market!",
    "In the world of stocks, only the strongest survive!",
    "Ready to dance with the bulls and bears?",
    "The power to win is in your hands!",
    "Your future fortune starts now!",
    "Wall Street isn’t for the faint of heart!",
    "Fortune smiles on the brave traders!",
    "Cash in, cash out—make every second count!",
    "The clock is ticking… are you trading?",
    "The game is simple: buy, sell, profit!",
    "One trade, one shot, one chance to win big!",
    "Fortunes rise and fall… but will you?",
    "It’s your turn to ride the market wave!",
    "The market is alive—are you in the game?",
    "Make moves, make money, make history!",
    "Big risks, bigger rewards… are you in?",
    "You can be a Wall Street legend!",
    "The stock market is your canvas—paint your masterpiece!",
    "Ready to build your empire, one trade at a time?",
    "There’s no such thing as too bold in the market!",
    "Fortunes favor the traders who dare!",
    "Your next move could make you a millionaire!",
    "Don’t just play the game… own it!",
    "Can you conquer the market chaos?",
    "Will you be the next market maverick?",
    "Turn your dreams into dividends!",
    "The market is moving… are you?",
    "Can you beat the market?",
    "You could be the next stock man!",
    "Think you’ve got what it takes to own Wall Street?",
    "The bulls are running… Are you?",
    "Fortune favors the bold! Ready to cash in?",
    "Buy low, sell high, live fast!",
    "Money never sleeps… and neither should you!",
    "The stock market waits for no one!",
    "Feeling lucky? Spin the financial wheel!",
    "Only the fearless survive the trading floor!",
    "Could you be the next Master of the Market?",
    "From rags to riches… if you play it right!",
    "Don’t just watch the ticker… be the ticker!",
    "Stocks are climbing… Are you?",
    "Trade fast, live large, retire rich!",
    "Welcome to the world of high stakes and high rewards!",
    "Cash in, cash out—make the market yours!",
    "Fortunes are made in minutes! Is yours one of them?",
    "The market is your playground… time to swing!",
    "Risk it all for the big win!"
]

